name: sizekit
description: A lightweight, high-performance package for pixel-perfect responsive UI. Effortlessly scale Figma designs, typography, and layouts across Mobile, Tablet, and Desktop.
version: 1.0.0
homepage: https://github.com/KunalTayal/sizekit
repository: https://github.com/KunalTayal/sizekit
issue_tracker: https://github.com/KunalTayal/sizekit/issues

# SEO Topics (Max 5 are displayed/indexed effectively on pub.dev)
topics:
  - responsive
  - figma
  - ui
  - layout
  - scaling

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

# Explicitly declaring platforms improves Pub Points
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: